""" adding bio and profile picture

Revision ID: 03691f25fd21
Revises: 7f6aeba6ac6d
Create Date: 2022-03-07 19:29:41.814073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03691f25fd21'
down_revision = '7f6aeba6ac6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
